### ISSUE TITLE
Create a list of lesson ideas

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-lab/reviews#1]
Short-format lesson ideas (1.5 to 3 hours):

* RMarkdown using the ecology dataset
* Shiny using the ecology dataset
* Linear models in R with the ecology dataset

Workshop ideas (1 to 2 days):

* Julia with ecology dataset

**Comment by ewallace** [comment]
Short-format lesson idea:

* Tabular data (tidyverse & ggplot) using a transcriptomics dataset

**Comment by tobyhodges** [comment]
@fmichonneau & @ewallace I am going to close this issue. If you have not yet proposed that the community works on any of the lesson ideas above, but would still like to, please [open a new issue in The Carpentries Incubator `proposals` repository](https://github.com/carpentries-incubator/proposals/issues/new?assignees=&labels=&template=issue_proposal.md).
