### ISSUE TITLE
Machine Learning with scikit-learn

### ISSUE THREAD

**Issue by colinsauze** [carpentries-lab/reviews#6]
I would like to propose a lesson on Machine Learning with scikit-learn and Python. 

I've created a lesson which I ran at a Spring school earlier this year. I then ran a session on this at Carpentry Connect Manchester last month where some additional ideas for developing this course were gathered. These still need to be implemented. 

repository: https://github.com/machinelearningcarpentry/machine-learning-novice
webpage: https://machinelearningcarpentry.github.io/machine-learning-novice/

Slides talking about the motivation for developing the course and experience of running it the first time: https://github.com/machinelearningcarpentry/machine-learning-novice/blob/ccmcr19/slides.pdf

Material from the discussion at carpentry connect:
https://github.com/machinelearningcarpentry/machine-learning-novice/tree/ccmcr19

**Comment by dvanic** [comment]
I'm happy to contribute to this/be involved. We've got an operational "ML R" and "ML python" courses I've developed and am running internally at Sydney Uni (across 2 days, though, and without neural nets). I'm trying to get them open sourced, but this may/may not be possible, so I'm happy to contribute to something broad by starting "from scratch" as well.

**Comment by ErinBecker** [comment]
Apologies @colinsauze for the delayed response on this. We're still working on getting the reviewer system set up for the Lab and want to provide people with the opportunity to share their lessons in the interim, so are directing all lesson proposals and materials to the Incubator at this time. 

I've just sent you an invitation to join the carpentries-incubator organization, which will give you the ability to change ownership of the repository to have it hosted in the Incubator. Once you've transferred it over, I'll make sure you have write access (along with anyone else you would like to give write access to). François and I are just now setting up the Incubator lessons website, which will list all lesson hosted on the Incubator. We're hoping to have that live later this week to coincide with the community calls happening tomorrow and Thursday (https://pad.carpentries.org/community-discussions). It would be great if you could join one of the calls, but I know it's late notice. 

My apologies again for the unforgivably late response. Hope you'll still want to host your lesson in the Incubator! Let me know what questions you have and I'll be sure to respond in a timely manner.

**Comment by tobyhodges** [comment]
Closing this since the lesson was transferred to the Incubator earlier this year (https://github.com/carpentries-incubator/proposals/issues/81)

https://github.com/carpentries-incubator/machine-learning-novice-sklearn
